### ISSUE TITLE
Unable to run swt-win64.jar

### ISSUE THREAD

**Issue by ttelang** [wangfei1975/superlog#1]
How to run swt-win64.jar ? Please provide instructions how can i run this application on Windows.

Running the command below
java -jar swt-win64.jar

gives error - Invalid or corrupt jarfile swt-win64.jar

**Comment by wangfei1975** [comment]
Thanks for message. swt-win64.jar is the SWT windows 64 library. The superlog  utilizes SWT for its UI.  No need to run swt-win64.jar. The correct way to lunch superlog is that download superlog-win64.jar from release tab:  

https://github.com/wangfei1975/superlog/releases

Run it in command line or double click it:
java -jar  superlog-win64.jar 

The project currently only provide windows 64 build. If you are using linux or Mac, you will need to download source code and compile it in eclipse with proper SWT lib.

**Comment by ttelang** [comment]
With the command below in Windows 7 Enterprise (SP1)
.java -jar superlog-win64.jar

I am getting the following message: 

Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 64-bit SW
T libraries on 32-bit JVM
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
        at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
        at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
        at feiw.AppContext.<init>(AppContext.java:23)
        at feiw.Slogmain.<clinit>(Slogmain.java:20)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:56)

My Java version is 
java -version

java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) Client VM (build 24.75-b04, mixed mode)

Any idea how can i resolve this. I am updating the JVM to 64 bit as suggested in the error message will revert back if this resolves the issue.

Thanks

**Comment by ttelang** [comment]
I was able to run the tool succesfully after updating my JDK to 64 bit version
