### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by Eccolala** [wangfei1975/superlog#14]
Hi, Thanks for your excellent work, Here is macOS High Serria, when I run "java -XstartOnFirstThread -jar superlog-osx.jar" to lanuch the app, cause a nullpointer exception: 

config file:/Users/aceler/.superlog
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.NullPointerException
	at feiw.SlogMainFrame$5.init(SlogMainFrame.java:280)
	at feiw.SlogMainFrame$DropdownListener.<init>(SlogMainFrame.java:135)
	at feiw.SlogMainFrame$5.<init>(SlogMainFrame.java:229)
	at feiw.SlogMainFrame.createToolBars(SlogMainFrame.java:229)
	at feiw.SlogMainFrame.createContents(SlogMainFrame.java:594)
	at feiw.SlogMainFrame.<init>(SlogMainFrame.java:84)
	at feiw.AppContext.<init>(AppContext.java:31)
	at feiw.Slogmain.<clinit>(Slogmain.java:20)
	... 3 more

**Comment by wangfei1975** [comment]
Thanks for posting. Can you try to re-build from latest version.
